security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    firewalls:
        oauth_token:
            pattern: ^/oauth/v2/token
            security: false

        api:
            pattern: ^/api
            fos_oauth: true
            stateless: true
            anonymous: true

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                use_forward: false
                use_referer: true
            logout: true
            anonymous: true
            remember_me:
                secret: "%secret%"

    access_control:
        - { path: ^/api, role: IS_AUTHENTICATED_ANONYMOUSLY, ip: [192.168.1.0/24, 127.0.0.1] }
        - { path: ^/api, role: ROLE_API }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/sym-admin, role: ROLE_ADMIN }

    role_hierarchy:
        ROLE_ADMIN:
            - ROLE_USER
            - ROLE_ADMIN_SETTING_COMPANY
            - ROLE_ADMIN_SETTING_SOCIAL
            - ROLE_ADMIN_SETTING_MAILCHIMP
        ROLE_ADMIN_BLOG:
            - ROLE_ADMIN_SETTING_BLOG
        ROLE_ADMIN_WIDGET:
            - ROLE_ADMIN_SETTING_WIDGET
        ROLE_ADMIN_WEBMASTER:
            - ROLE_ADMIN_SETTING_WEBMASTER
            - ROLE_ADMIN_SETTING_SEO
        ROLE_SUPER_ADMIN:
            - ROLE_ADMIN
            - ROLE_SUPER_EXTEND
            - ROLE_ADMIN_BLOG
            - ROLE_ADMIN_WIDGET
            - ROLE_ADMIN_IMAGE
            - ROLE_ADMIN_SETTING
            - ROLE_ADMIN_PAGE
            - ROLE_ADMIN_USER
            - ROLE_ADMIN_EVENT
            - ROLE_ADMIN_WEBMASTER
            - ROLE_ADMIN_EDITABLE
            - ROLE_ADMIN_STYLIZER
            - ROLE_ADMIN_SETTING_ADVANCED
            - ROLE_API
            - ROLE_ADMIN_FORM_BUILDER
