admin_image:
    path: /
    methods: [GET]
    defaults:
        _controller: symedit.controller.image:indexAction
        _sylius:
            template: "@SymEdit/Admin/Image/index.html.twig"
            paginate: false
            limit: false

admin_image_json:
    path: /list.{_format}
    requirements:
        _format: json
    defaults:
        _format: json
        _controller: symedit.controller.image:jsonAction
        _sylius:
            paginate: false

admin_image_dialog:
    path: /dialog
    methods: [GET, POST]
    defaults:
        _controller: symedit.controller.image:indexAction
        _sylius:
            template: "@SymEdit/Admin/Image/dialog.html.twig"
            paginate: false
            limit: false

admin_image_create:
    path: /new
    methods: [GET, POST]
    defaults:
        _controller: symedit.controller.image:createAction
        _sylius:
            template: "@SymEdit/Admin/Image/new.html.twig"
            redirect: admin_image_update

admin_image_quick_upload:
    path: /quick-upload
    methods: [POST]
    defaults:
        _controller: symedit.controller.image:quickUploadAction

admin_image_update:
    path: /{id}/edit
    methods: [GET, PUT, POST]
    defaults:
        _controller: symedit.controller.image:updateAction
        _sylius:
            template: "@SymEdit/Admin/Image/edit.html.twig"
            redirect:
                route: admin_image_update
                parameters: { id: $id }

admin_image_delete:
    path: /{id}/delete
    methods: [DELETE]
    defaults:
        _controller: symedit.controller.image:deleteAction
        _sylius:
            redirect: admin_image
