admin_user:
    path: /
    methods: [GET]
    defaults:
        _controller: symedit.controller.user:indexAction
        _sylius:
            template: "@SymEdit/Admin/User/index.html.twig"
            criteria:
                admin: true
            sorting:
                username: asc

admin_user_create:
    path: /new
    methods: [GET, POST]
    defaults:
        _controller: symedit.controller.user:createAction
        _sylius:
            template: "@SymEdit/Admin/User/new.html.twig"
            factory: createAdmin
            redirect:
                route: admin_user_update
                parameters: { id: resource.id }

admin_user_show:
    path: /{id}
    methods: [GET]
    defaults:
        _controller: symedit.controller.user:showAction
        _sylius:
            template: "@SymEdit/Admin/User/show.html.twig"

admin_user_update:
    path: /{id}/edit
    methods: [GET, PUT, POST]
    defaults:
        _controller: symedit.controller.user:updateAction
        _sylius:
            template: "@SymEdit/Admin/User/edit.html.twig"
            redirect:
                route: admin_user_update
                parameters: { id: $id }
