contact:
    path: /
    defaults:
        _controller: symedit.controller.contact:indexAction

contact_success:
    path: /success
    defaults:
        _controller: symedit.controller.contact:successAction
