webmaster_google_verify:
    path: /google{request_code}.html
    requirements:
        request_code: "[a-z0-9]{16}"
    defaults:
        _controller: SymEditBundle:Webmaster:googleVerify

webmaster_bing_verify:
    path: /BingSiteAuth.{_format}
    requirements:
        _format: xml
    defaults:
        _controller: SymEditBundle:Webmaster:bingVerify
        _format: xml

robots:
    path: /robots.{_format}
    requirements:
        _format: txt
    defaults:
        _controller: SymEditBundle:Webmaster:robots
        _format: txt

sitemap:
    path: /sitemap.{_format}
    requirements:
        _format: xml
    defaults:
        _controller: SymEditSitemapBundle:Sitemap:index
        _format: xml
